config/routes.rb
Rails.application.routes.draw do

  root 'users#index'

  #user signup
  get '/', to: 'users#index', as: 'home'
  post '/signup', to: 'users#create', as: 'signup'
  get '/info', to: 'users#info'
  get '/education', to: 'users#education'

  #user login
  post '/login', to: 'sessions#create', as:'login'
  delete '/logout', to: 'sessions#destroy', as: 'logout'

  #News
  get '/news/:id', to: 'news#show', as: 'news'
  get '/news/edit/:id', to: 'news#edit', as: 'edit_news'
  put '/news/update/:id', to: 'news#update', as: 'update_news'
  get '/new/news', to:'news#new', as: 'news_page'
  post '/new/create', to: 'news#create', as: 'create_news'

  #ThreeW
  get '/edit/wh/:id', to: 'threews#edit', as: 'edit_wh'
  put '/update/wh/:id', to: 'threews#update', as: 'update_wh'

  #Direction Page
  get '/direction', to: 'directions#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/direction.rb
class Direction < ApplicationRecord
end

app/models/new.rb
class New < ApplicationRecord
end

app/models/threew.rb
class Threew < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
  include UsersHelper
  include NewsHelper
  include ThreewsHelper
end

app/controllers/directions_controller.rb
class DirectionsController < ApplicationController
  def index
    change_position("direction")
    @direction = Direction.last
  end
end

app/controllers/news_controller.rb
class NewsController < ApplicationController
  before_action :authentication, only: [:update, :edit, :new, :create, :destroy]
  def show
    @news = New.find(params[:id])
  end

  def new
    @news = New.new
  end

  def create
    @news = New.new(news_params)
    if @news.save
      flash[:update] = "#{@news.title} Has Been Created"
      redirect_to root_path
    else
      flash[:failed] = "Failed to Create News"
      redirect_to news_create_page
    end
  end

  def edit
    @news = New.find(params[:id])
  end

  def update
    @news = New.find(params[:id])
    if @news.update(news_params)
      flash[:update] = "Update Successfully"
      redirect_to root_path
    else
      flash[:failed] = "Update Failed"
      redirect_to root_path
    end
  end

  def destroy
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    @user = User.find_by_username(login_params[:username])

    if @user && @user.authenticate(login_params[:password])
      login(@user)
      flash[:success] = "Successfully logged in."
      redirect_to root_path
    else
      flash[:error] = "Invalid username or password"      # <--- Add this flash notice

      redirect_to root_path
    end
  end

  def destroy

    logout
    redirect_to root_path
  end


end

app/controllers/threews_controller.rb
class ThreewsController < ApplicationController
  before_action :authentication
  def edit
    @threew = Threew.find(params[:id])
  end

  def update
    @threew = Threew.find(params[:id])
    if @threew.update(threew_params)
      flash[:update] = "Update Successfully"
      redirect_to root_path
    else
      flash[:failed] = "Update Failed"
      redirect_to root_path
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @new = New.all
    @threew = Threew.all
    change_position("home")
  end
  def create
    if user_params[:password] != user_params[:confirm_password]
      flash[:error] = "Password did not match"
      redirect_to home_path
    elsif params[:inviteCode] != "TMclub21sm"
      flash[:error] = "Invalid Invitation Code"
      redirect_to home_path
    else
      @user = User.new(user_params)
      if @user.save
        login(@user)
        flash[:success] = "Welcome!"
        redirect_to home_path
      else
        flash[:error] = @user.errors.full_messages[0]
        redirect_to home_path
      end
    end
  end
  def destroy
    logout
    flash[:success] ="Successfully Logged Out"
    redirect_to home_path
  end



  def info
    change_position("info")
    render "info"
  end

  def education
    change_position("education")
    render "education"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/directions_helper.rb
module DirectionsHelper
end

app/helpers/news_helper.rb
module NewsHelper
  def news_params
    params.require(:news).permit(:title, :details)
  end

end

app/helpers/sessions_helper.rb
module SessionsHelper
  def login(user)
    session[:user_id] = user.id
    @current_user = user
    cookies.signed[:user_id] = current_user.id
  end

  def logout
    session[:user_id] = "none"
    @current_user = false
    cookies.signed[:user_id] = nil
  end

  def current_user
    @current_user ||= User.find_by_id(session[:user_id])
  end

  def authentication
    if !current_user
      flash[:error] = "You are not authorized to the page"
      redirect_to root_path
    end
  end

  def login_params
    params.require(:user).permit(:username, :password)
  end

  def change_position(position)
    @position = position
  end

  def current_position
    @position ||= nil
  end

end

app/helpers/threews_helper.rb
module ThreewsHelper
  def threew_params
    params.require(:threew).permit(:title, :details)
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def user_params
    params.require(:user).permit(:username, :password, :confirm_password)
  end
end

app/views/directions/index.html.erb
<div class="col-sm-10 offset-sm-1" id="main_container">
  <div class="row">
    <div class="col-sm-5">
      <div class="row">
        <h1 class="section_title">Table Topic</h1>
        <div class="container">
          <h2 class="subhead_orange">Date</h2>
          <h4><%=@direction.topic_date%></h4>
          </br>
          <h2 class="subhead_orange">Theme</h2>
          <h4><%=@direction.topic_theme%></h4>
        </div>
      </div>
      </br>
      </br>
      <div class="row">
        <h1 class="section_title">Schedule</h1>
        <h4><a id="download_link" href="#">Click to download the full meeting Schedule for the coming week.</a></h4>
      </div>
      </br>
      </br>
      <div class="row">
        <h1 class="section_title">Events</h1>
        <div class="container">
          <h2 class="subhead_orange">Date</h2>
          <h4><%=@direction.event_date%></h4>
          <h2 class="subhead_orange">About</h2>
          <h4><%=@direction.event_detail%></h4>
        </div>
      </div>
    </div>
    <div class="col-sm-7">
      <div class="row">
        <div class="col-12" id="map">
        </div>
        <button type="button" name="button" id="mapBtn" class="btn btn-primary">Click for detail Map</button>
      </div>
      <div class="row" id="building_img_container">
        <div class="building_img">
          <h1>The Building</h1>
          <p>Image 1</p>
        </div>
        <div class="building_img">
          <h1>Meeting Room</h1>
          <p>Image 2</p>
        </div>
      </div>
      <div class="row">
        <div class="col-12 www">
          <h1 class="head_blue">Where?</h1>
          <h2 class="subhead_orange">Earth, Wind and Floor Resturant</h2>
          <p>2222 Wilshire Blvd </br>
            Santa Monica, CA 90404
          </p>
        </div>
        <div class="col-12 www">
          <h1 class="head_blue">When?</h1>
          <h2 class="subhead_orange">Tuesdays 7:00 pm to 9:00 pm</h2>
          <p>Meeting starts promptly</br>
          Please arrive 15 minutes early to meet our members</p>
        </div>
        <div class="col-12 www">
          <h1 class="head_blue">Parking?</h1>
          <p>Valet parking available at the back of the restruant</br>
          Metered street parking are free after 6:00 pm</p>
        </div>


      </div>
    </div>
  </div>
</div>

app/views/layouts/_footer.html.erb
<footer >
  <div class="col-sm-4">

  </div>
  <div class="col-sm-4">
    <span class="footer">(310)829-7829</span>
    </br>
    <span class="footer">Info@SMClub21.org</span>
  </div>
  <div class="col-sm-4" id="social-media">
    <a href="#"><img class="media-icon" src='/Instragram.png' /></a>
    <a href="#"><img class="media-icon" src='/google plus.png' /></a>
    <a href="#"><img class="media-icon" src='/twitter.png' /></a>
    <a href="#"><img class="media-icon" src='/facebook.png' /></a>
  </div>
</footer>

app/views/layouts/_navbar.html.erb
<div id="nav">
  <h1 id="logo-container">
    <img id="nav-logo" src='/Club 21.png' />
  </h1>
  <nav class=" navbar-expand-lg navbar-light bg-faded navi">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarResponsive">

      <div class="col-md-12">
        <%if current_position === "home"%>
        <div class="nav-align">
          <a class="col-md-3 nav-item nav-link" id="current" href="/">Home</a>
          <a class="col-md-3 nav-item nav-link" href="/direction">Direction</a>
          <a class="col-md-3 nav-item nav-link" href="/info">Info</a>
          <a class="col-md-3 nav-item nav-link" href="/education">Education</a>
        </div>
        <%elsif current_position === "direction"%>
        <div class="nav-align">
          <a class="col-md-3 nav-item nav-link" href="/">Home</a>
          <a class="col-md-3 nav-item nav-link" id="current" href="/direction">Direction</a>
          <a class="col-md-3 nav-item nav-link" href="/info">Info</a>
          <a class="col-md-3 nav-item nav-link" href="/education">Education</a>
        </div>
        <%elsif current_position === "info"%>
        <div class="nav-align">
          <a class="col-md-3 nav-item nav-link" href="/">Home</a>
          <a class="col-md-3 nav-item nav-link" href="/direction">Direction</a>
          <a class="col-md-3 nav-item nav-link" id="current" href="/info">Info</a>
          <a class="col-md-3 nav-item nav-link" href="/education">Education</a>
        </div>
        <%elsif current_position === "education"%>
        <div class="nav-align">
          <a class="col-md-3 nav-item nav-link" href="/">Home</a>
          <a class="col-md-3 nav-item nav-link" href="/direction">Direction</a>
          <a class="col-md-3 nav-item nav-link" href="/info">Info</a>
          <a class="col-md-3 nav-item nav-link" id="current" href="/education">Education</a>
        </div>
        <%else %>
        <div class="nav-align">
          <a class="col-md-3 nav-item nav-link" href="/">Home</a>
          <a class="col-md-3 nav-item nav-link" href="/direction">Direction</a>
          <a class="col-md-3 nav-item nav-link" href="/info">Info</a>
          <a class="col-md-3 nav-item nav-link" href="/education">Education</a>
        </div>
        <%end%>
      </div>

    </div>
  </nav>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ToastMaster</title>
    <%= csrf_meta_tags %>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
    <!-- STYLESHEETS -->
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <!-- HAVE TO INCLUDE VALIDATOR TO USE VALIDATOR!!!! THIS THING TOOK ME AN HOUR TO SOLVE -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/1000hz-bootstrap-validator/0.11.5/validator.min.js"></script>
    <script src="https://use.fontawesome.com/6f8b4ecbb1.js"></script>
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
    <!-- FONTS -->
    <link href="https://fonts.googleapis.com/css?family=PT+Mono|Ubuntu" rel="stylesheet">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "/layouts/navbar" %>

    <h1 class="text-center" id="main_title">Toast Master Santa Monica Club 21</h1>
    <% flash.each do |name, msg| %>
      <% if name == "update" %>
        <p class="alert alert-success">
          <strong><%= msg %></strong>
        </p>
      <% elsif name == "failed" %>
        <p class="alert alert-danger">
          <strong><%= msg %></strong>
        </p>
      <% end %>
    <% end %>
    <div class="main_content">
      <%= yield %>
    </div>
    <%= render "/layouts/footer" %>
    <script>
     function initMap() {
       var uluru = {lat: 34.0330398, lng: -118.4828856};
       var map = new google.maps.Map(document.getElementById('map'), {
         zoom: 18,
         center: uluru
       });

       var marker = new google.maps.Marker({
         position: uluru,
         label: "X",
         map: map
       });
     }
   </script>
    <script async defer
   src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCPJ_x1unjVjwjwj_nXHfu23nzuhGNMkII&callback=initMap">
   </script>
  </body>
</html>

app/views/news/edit.html.erb
<h1>asd</h1>

app/views/news/new.html.erb
<div class="form">
  <%= form_with scope: :news, url: create_news_path, class: "form-horizontal" do |form| %>
  <div class="form-group">
  		<%= form.label :title, "Title:" %>
  		<%= form.text_field(:title, class: 'form-control') %>
  </div>
  <div class="form-group">
  		<%= form.label :details, "Invite Users:" %>
  		<%= form.text_area(:details, class: 'form-control') %>
  </div>
  <div class="form-group">
  		<%= form.submit('Submit', class: 'btn-sm btn-primary') %>
  </div>
  <% end %>
</div>

app/views/news/show.html.erb
<div class="container">
  <h1><%=@news.title%></h1>
  <p><%=@news.details%></p>
</div>

app/views/threews/edit.html.erb
<div class="form">
  <%= form_with scope: :threew, url: update_wh_path(@threew.id), class: "form-horizontal", method: :PUT do |form| %>
  <h1><%=@threew.title%></h1>
  <div class="form-group">
  		<%= form.label :details, "Details:" %>
  		<%= form.text_area(:details, class: 'form-control') %>
  </div>
  <div class="form-group">
  		<%= form.submit('Submit', class: 'btn-sm btn-primary') %>
  </div>
  <% end %>
</div>

app/views/users/_flashMsg.html.erb
<% flash.each do |name, msg| %>
  <% if name == "success" %>
    <p class="alert alert-success">
  <% else %>
    <p class="alert alert-danger">
  <% end %>
    <strong> <%= name.capitalize %>: <%= msg %> </strong>
  </p>
<% end %>

app/views/users/_logForm.html.erb
<div class="login" id="card">
  <%= render "/users/flashMsg"%>
    <div class="front signin_form">
      <h3 class="member_border">Member Login</h3>
      <form class="form-horizontal login" action="/login" accept-charset="UTF-8" data-remote="true" method="post">
        <input name="utf8" type="hidden" value="✓"><input type="hidden" name="authenticity_token" value="ipL5QxQtMHkdTbctqyAa1kweTecIY7OBxFHctrc5a4KGh4mjIljrjxIgYgt3mFRiaCgitLmVqMDfRSMvNlHzKA==">
            <div class="form-group">
                <div class="input-group">
                    <input class="form-control" type="text" name="user[username]" placeholder="Username">
                    <span class="input-group-addon">
                        <i class="glyphicon glyphicon-user"></i>
                    </span>
                </div>
            </div>
            <div class="form-group">
                <div class="input-group">
                    <input class="form-control" type="password" name="user[password]" placeholder="Password">
                    <span class="input-group-addon">
                        <i class="glyphicon glyphicon-lock"></i>
                    </span>
                </div>
            </div>

            <div class="form-group sign-btn">
                <input type="submit" name="commit" value="Log In" class="btn btn-primary" data-disable-with="Log In">
                <p><strong>New Member?</strong><br><a href="#" id="flip-btn" class="signup signup_link">Sign up for a new account</a></p>
            </div>
        </form>
      </div>
      <div class="back signup_form" style="display:none">
        <h3 class="member_border">New Member Signup</h3>
        <form class="form-horizontal" action="/signup" accept-charset="UTF-8" data-remote="true" method="post"><input name="utf8" type="hidden" value="✓">
          <input type="hidden" name="authenticity_token" value="q4p2w8twSz36SAM92wUrWnxGOK+75nmY/bWCEFcawdkPHY+AbwhN0F5cJZ3Uw4gINLTMH9+P8S5DnonBAoWzvw==">
            <div class="form-group">
                <div class="input-group">
                    <input class="form-control" id="username_input" type="text" name="user[username]" placeholder="Username">
                    <span class="input-group-addon">
                        <i class="glyphicon glyphicon-user"></i>
                    </span>
                </div>
            </div>
            <div class="form-group">
                <div class="input-group">
                    <input class="form-control" type="password" name="user[password]" placeholder="Password">
                    <span class="input-group-addon">
                        <i class="glyphicon glyphicon-lock"></i>
                    </span>
                </div>
            </div>
            <div class="form-group">
                <div class="input-group">
                    <input class="form-control" type="password" name="user[confirm_password]" placeholder="Confirm Password">
                    <span class="input-group-addon">
                        <i class="glyphicon glyphicon-lock"></i>
                    </span>
                </div>
            </div>
            <div class="form-group">
                <div class="input-group">
                    <input class="form-control" type="password" name="inviteCode" placeholder="Invitation Code">
                    <span class="input-group-addon">
                        <i class="glyphicon glyphicon-lock"></i>
                    </span>
                </div>
            </div>


            <div class="form-group sign-btn">
                <input type="submit" name="commit" value="Sign Up" class="btn btn-primary" data-disable-with="Sign Up">
                <br><br>
                <p>You have already Account So <a href="#" id="unflip-btn" class="signup">Log in</a></p>
            </div>
        </form>
      </div>
  </div>

app/views/users/education.html.erb
<h1>Education Page</h1>

app/views/users/index.html.erb
<div class="col-sm-10 offset-sm-1" id="main_container">
  <div class="row">
    <div class="col-sm-4">
      <div class="row" id="member_section">
        <div class="container">
          <%if current_user%>
            <h2 class="text-center member_border">Member Dashboard</h2>
            <h3 class="text-center">
              <%=link_to "Create News", news_page_path, class:"white-pencil"%>
            </h3>
            <h3 class="text-center" id="logout">
              <%= link_to "LogOut", logout_path, class:"white-pencil", method: :delete%>
            </h3>
          <%else%>
          <%= render "/users/logForm" %>
          <%end%>
        </div>
      </div>
      <div class="row">
          <h1 class="section_title">News</h1>
        <div class="container" id="news_container">
          <%@new.order(updated_at: :desc).each do |news|%>
            <%if current_user%>
            <h3><%= link_to news.title, news_path(news.id)%>
              <%=link_to edit_news_path(news.id) do%>
              <i class="fa fa-pencil-square-o float-right" aria-hidden="true"></i>
              <%end%>
            </h3>
            <%else%>
            <h3><%= link_to news.title, news_path(news.id)%></h3>
            <%end%>
            <div class="details_container" id="news-<%=news.id%>">
              <%=news.details%>
            </div>
            <i class="new-down fa btn fa-chevron-down" data-id="<%=news.id%>" aria-hidden="true"></i>
          <%end%>
        </div>

      </div>
    </div>
    <div class="col-sm-8">
      <%@threew.order(created_at: :asc).each do |w|%>
      <div class="Threew">
        <%if current_user%>
        <h1 class="section_title">
          <%=w.title%>
          <%=link_to edit_wh_path(w.id), class:"white-pencil" do%>
          <i class=" fa fa-pencil-square-o float-right" aria-hidden="true"></i>
          <%end%>
        </h1>
        <%else%>
        <h1 class="section_title"><%=w.title%></h1>
        <%end%>
        <div class="w_card" id="3w-<%=w.id%>">
          <%w.details.split("\n").each do |text|%>
            <%=text%>
            </br>
          <%end%>
        </div>
        <i class="3w fa btn fa-chevron-down" data-id="3w-<%=w.id%>" aria-hidden="true"></i>
      </div>
      <%end%>
    </div>
  </div>
</div>

app/views/users/info.html.erb
<h1>Info Page</h1>